name: Flake8 Linting

on:
  push:
    branches: [ "main", "iteration4" ]
  pull_request:
    branches: [ "main", "iteration4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies, including Flake8 and any project-specific requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-docstrings
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint the code with Flake8
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source

          # Exit-zero treats all errors as warnings. Useful for enforcing the 127-character max line length
          flake8 . --count --max-complexity=10 --max-line-length=127 --ignore=F401 --exclude=polls/tests,polls/migrations
